import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { increment, decrement, setStep } from "../reducers/counter";
import { RootState } from "../store";
import CounterValue from "@/components/counter-value";
import CounterReset from "@/components/counter-reset";

export default function Home() {
  const count = useSelector((state: RootState) => state.counter);
  const dispatch = useDispatch();
  const handleStepChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const newStep = parseInt(event.target.value);
    dispatch(setStep(newStep));
  };
  return (
    <>
      <Head>
        <title>Redux Toolkit</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2> Hello from redux toolkit</h2>
        <button onClick={() => dispatch(increment())}>Increment</button>
        <button onClick={() => dispatch(decrement())}>Decrement</button>
        <input type="number" value={count.step} onChange={handleStepChange} />
        <CounterValue />
        <CounterReset />
      </main>
    </>
  );
}
